### ISSUE TITLE
Item loss (or gain, I guess?) when throwing materials on the ground

### ISSUE THREAD

**Issue by Sul4urx** [Vanderflys/minions#1]
**Minecraft version:** 1.20.2
**Datapack version:** 1.1.1 (Downloaded from Modrinth)

Description:
----
When throwing the materials (i.e cobblestone, dirt) on the ground, The function doesn't seem to work correctly and instead of having to throw a stack of the material, you can throw any number of materials and it will turn into 1 enchanted of that material. Heck you can even throw more than 1 and less than 64 enchanted materials (In other words, 1 < number of enchanted materials < 64) onto the ground and it will turn back to 1.

Steps to Reproduce:
----
1. Throw any number of cobblestones (or any material) on the ground
2. It will turn into 1 enchanted cobblestone (material), no matter how many cobblestones there were.

**Expected behavior:** You can only turn the materials if there were exactly 64 of them and not enchanted
**Actual behavior:** It only checks for the material, not the count nor the nbt tags.

**Additional Information;** Seems like the data pack posted in github (right here, on the "Code" tab) is outdated...

**Comment by Vanderflys** [comment]
Fixed bug report (1) and thank you for reporting it!
